name = "NucleosomeInference"
uuid = "4d185f6f-9c3f-4b7c-9166-636828f15909"
authors = ["Nick Owens <owensnick@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
